version: '3.8'

services:
  neo4j:
    image: neo4j:5.15
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/neo4jneo4j
    volumes:
      - neo4j_data:/data
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "neo4jneo4j", "RETURN 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      - neo4j
    environment:
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: neo4jneo4j    
    stdin_open: true # Keep the container's STDIN open
    tty: true        # Allocate a pseudo-TTY
    volumes:
      - ./app_data:/app/output
    command: ["/bin/bash"] # Start the container with an interactive shell

volumes:
  neo4j_data: